all : readline1 readline2 readline3 readline4

readline1 : readline1.c
	gcc -o readline1 readline1.c

readline2 : readline2.cpp
	g++ -o readline2 readline2.cpp

readline3 : readline3.cpp
	g++ -o readline3 readline3.cpp

readline4 : readline4.cpp
	g++ -o readline4 readline4.cpp

clean:
	rm readline1 readline2 readline3 readline4
